/**
 * Phase 8 — side-by-side "Prediction vs Intervention" card.
 *
 * The MOST important UI on the project: a recruiter glancing at the
 * student page should understand the difference between traditional ML
 * and EduRAG in under 30 seconds.
 *
 * Left column = "Traditional Prediction" — predicted risk, top
 *   predictors, the honest disclaimer that this only tells you WHO is at
 *   risk, not what to change.
 * Right column = "EduRAG Causal Output" — top intervention with projected
 *   gain + CI + confidence chip, with a pointer to the full ranked list.
 * Footer = insight chips generated by `buildComparison()`.
 */

import Link from "next/link";

import {
  buildComparison,
  type ComparisonInsight,
  type ComparisonRow,
  type PredictionResult,
} from "@/features/baseline-ml";
import { formatDecimal, formatDelta } from "@/lib/formatters";
import { confidenceMetaFor } from "@/lib/confidence-label";
import {
  featureLabel,
  interventionLabel,
  predictionFeatureLabel,
} from "@/lib/intervention-language";
import type { StudentInterventionRow } from "@/server/queries/students";

import ConfidenceChip from "./ConfidenceChip";

interface Props {
  studentExternalId: string;
  prediction: PredictionResult | null;
  interventions: StudentInterventionRow[];
}

export default function PredictionVsInterventionCard({
  studentExternalId,
  prediction,
  interventions,
}: Props) {
  const summary = buildComparison({
    studentId: studentExternalId,
    prediction,
    interventions,
  } as ComparisonRow);

  return (
    <section className="rounded-xl border border-slate-200 bg-white shadow-sm overflow-hidden">
      <header className="border-b border-slate-200 bg-gradient-to-r from-slate-50 to-white px-5 py-3">
        <h2 className="text-base font-semibold text-slate-900">
          Prediction vs Intervention
        </h2>
        <p className="mt-1 text-xs text-slate-500">
          A traditional risk score tells you <strong>WHO</strong> needs attention. EduRAG&apos;s
          causal layer tells you <strong>WHAT TO CHANGE</strong>. Both views are shown so
          you can decide.
        </p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-2 divide-y lg:divide-y-0 lg:divide-x divide-slate-200">
        {/* ---- Prediction column --------------------------------------- */}
        <div className="p-5 space-y-4">
          <div className="flex items-baseline justify-between gap-2">
            <h3 className="text-sm font-semibold text-slate-900">
              Traditional Prediction
            </h3>
            <span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide text-slate-600">
              statistical model
            </span>
          </div>

          {prediction === null ? (
            <EmptyPanel
              title="No prediction yet"
              hint={
                <>
                  Run <code className="rounded bg-slate-100 px-1.5 py-0.5">npm run ml:predict</code>
                  {" "}to populate this panel.
                </>
              }
            />
          ) : (
            <>
              <div className="grid grid-cols-2 gap-3">
                <Stat
                  label="P(at-risk)"
                  value={`${(prediction.predictedRiskProb * 100).toFixed(1)}%`}
                  tone={prediction.riskClass === "at-risk" ? "warning" : "neutral"}
                />
                <Stat
                  label="Predicted class"
                  value={
                    prediction.riskClass === "at-risk"
                      ? "At risk"
                      : prediction.riskClass === "borderline"
                        ? "Borderline"
                        : "On track"
                  }
                  tone={prediction.riskClass === "at-risk" ? "warning" : "neutral"}
                />
              </div>

              <div>
                <h4 className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">
                  Top predictors (|β|, standardised)
                </h4>
                <ul className="mt-1.5 space-y-1.5">
                  {prediction.featureImportance.slice(0, 3).map((fi) => (
                    <li
                      key={fi.feature}
                      className="flex items-center gap-3 text-xs"
                    >
                      <span className="min-w-[140px] text-slate-700">
                        {predictionFeatureLabel(fi.feature)}
                      </span>
                      <Bar value={fi.absValue} max={maxAbs(prediction.featureImportance)} />
                      <span className="w-12 text-right font-mono text-slate-600">
                        {formatDelta(fi.value, 3)}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-[11px] text-slate-600">
                <p>
                  <strong>What this is:</strong> a probabilistic risk score from a
                  logistic-regression baseline. It identifies the
                  <em> who</em>.
                </p>
                <p className="mt-1">
                  <strong>What this is NOT:</strong> an intervention recommendation.
                  Feature importance is not the same thing as causal effect.
                </p>
              </div>
            </>
          )}
        </div>

        {/* ---- Intervention column ------------------------------------- */}
        <div className="p-5 space-y-4 bg-emerald-50/30">
          <div className="flex items-baseline justify-between gap-2">
            <h3 className="text-sm font-semibold text-slate-900">
              EduRAG Causal Output
            </h3>
            <span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide text-emerald-800">
              causal layer
            </span>
          </div>

          {interventions.length === 0 ? (
            <EmptyPanel
              title="No interventions yet"
              hint={
                <>
                  Run <code className="rounded bg-slate-100 px-1.5 py-0.5">npm run causal:simulate</code>
                  {" "}to populate this panel.
                </>
              }
            />
          ) : (
            <>
              <TopInterventionPanel intervention={interventions[0]!} />

              {interventions.length > 1 && (
                <ul className="mt-2 space-y-1 text-[11px] text-slate-600">
                  <li className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">
                    Other ranked interventions
                  </li>
                  {interventions.slice(1, 3).map((intv, i) => (
                    <li
                      key={intv.interventionName}
                      className="flex items-center gap-2"
                    >
                      <span className="font-mono text-slate-400">{i + 2}.</span>
                      <span>{interventionLabel(intv.interventionName)}</span>
                      <span className="ml-auto font-mono">
                        {formatDelta(intv.projectedGrade - intv.baselineGrade, 2)} pts
                      </span>
                    </li>
                  ))}
                </ul>
              )}

              <div className="rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-[11px] text-emerald-900">
                <p>
                  <strong>What this is:</strong> a counterfactual estimate of the
                  cohort-average effect of a behavioural change, applied to this
                  student. It identifies the <em>what to change</em>.
                </p>
                <p className="mt-1">
                  <strong>Reminder:</strong> not a personal guarantee — see the
                  refutation-derived confidence chip and the CI range.
                </p>
              </div>
            </>
          )}
        </div>
      </div>

      {/* ---- Insights footer ----------------------------------------- */}
      {summary.insights.length > 0 && (
        <footer className="border-t border-slate-200 bg-slate-50 px-5 py-4">
          <h3 className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">
            Comparison insights
          </h3>
          <ul className="mt-2 space-y-2 text-xs">
            {summary.insights.map((ins, i) => (
              <InsightItem key={i} insight={ins} />
            ))}
          </ul>
          <p className="mt-3 text-[10px] text-slate-400">
            See <Link href="/comparison" className="underline">Comparison · cohort view</Link>{" "}
            for every student in this course.
          </p>
        </footer>
      )}
    </section>
  );
}

// ---- subcomponents --------------------------------------------------------

function EmptyPanel({ title, hint }: { title: string; hint: React.ReactNode }) {
  return (
    <div className="rounded-md border border-dashed border-slate-300 bg-white/60 px-4 py-3 text-xs text-slate-500">
      <p className="font-medium text-slate-700">{title}</p>
      <p className="mt-1">{hint}</p>
    </div>
  );
}

function Stat({
  label,
  value,
  tone,
}: {
  label: string;
  value: string;
  tone: "neutral" | "warning";
}) {
  const toneClasses =
    tone === "warning"
      ? "border-rose-200 bg-rose-50 text-rose-900"
      : "border-slate-200 bg-white text-slate-900";
  return (
    <div className={`rounded-md border px-3 py-2 ${toneClasses}`}>
      <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">
        {label}
      </p>
      <p className="mt-0.5 text-base font-semibold">{value}</p>
    </div>
  );
}

function Bar({ value, max }: { value: number; max: number }) {
  const width = max > 0 ? Math.max(2, Math.min(100, (value / max) * 100)) : 0;
  return (
    <div className="h-1.5 flex-1 rounded-full bg-slate-100">
      <div
        className="h-full rounded-full bg-slate-400"
        style={{ width: `${width}%` }}
      />
    </div>
  );
}

function TopInterventionPanel({ intervention }: { intervention: StudentInterventionRow }) {
  const gain = intervention.projectedGrade - intervention.baselineGrade;
  const meta = confidenceMetaFor(intervention.confidence);
  return (
    <div className="rounded-md border border-emerald-200 bg-white p-3">
      <div className="flex items-baseline justify-between gap-2">
        <p className="text-sm font-semibold text-slate-900">
          {interventionLabel(intervention.interventionName)}
        </p>
        <ConfidenceChip level={intervention.confidence} size="sm" />
      </div>
      <p className="mt-0.5 text-[11px] text-slate-500">
        Treatment: {featureLabel(intervention.treatment)} · {meta.hint}
      </p>
      <div className="mt-2 grid grid-cols-3 gap-2 text-xs">
        <div>
          <p className="text-[10px] uppercase tracking-wide text-slate-500">
            Projected gain
          </p>
          <p className="text-lg font-semibold text-emerald-700">
            {formatDelta(gain, 2)}
          </p>
        </div>
        <div>
          <p className="text-[10px] uppercase tracking-wide text-slate-500">
            Range
          </p>
          <p className="font-mono text-slate-700">
            [{formatDecimal(intervention.projectedLow - intervention.baselineGrade, 2)},{" "}
            {formatDecimal(intervention.projectedHigh - intervention.baselineGrade, 2)}]
          </p>
        </div>
        <div>
          <p className="text-[10px] uppercase tracking-wide text-slate-500">
            Applied Δ
          </p>
          <p className="font-mono text-slate-700">{formatDelta(intervention.appliedDelta, 2)}</p>
        </div>
      </div>
    </div>
  );
}

function InsightItem({ insight }: { insight: ComparisonInsight }) {
  const dot =
    insight.tone === "positive"
      ? "bg-emerald-500"
      : insight.tone === "warning"
        ? "bg-rose-500"
        : "bg-slate-400";
  return (
    <li className="flex gap-3">
      <span className={`mt-1.5 inline-block h-1.5 w-1.5 shrink-0 rounded-full ${dot}`} />
      <div>
        <p className="font-medium text-slate-900">{insight.headline}</p>
        <p className="text-slate-600">{insight.detail}</p>
      </div>
    </li>
  );
}

function maxAbs(items: ReadonlyArray<{ absValue: number }>): number {
  let m = 0;
  for (const it of items) if (it.absValue > m) m = it.absValue;
  return m;
}
