/**
 * Phase 11 — status labels + allowable transitions.
 *
 * Pure. The persisted statuses are intentionally close to a flat set —
 * we don't model a strict state machine because real advisors change
 * their mind. `canTransition` exists for UI affordance (greying out
 * impossible buttons) and tests, not for hard enforcement.
 */

import type { DecisionStatus } from "./types";

export const STATUS_LABEL: Record<DecisionStatus, string> = {
  proposed: "Proposed",
  accepted: "Accepted",
  rejected: "Rejected",
  deferred: "Deferred",
  completed: "Completed",
};

export const STATUS_HINT: Record<DecisionStatus, string> = {
  proposed: "Recommendation generated by the causal engine; no advisor decision yet.",
  accepted: "Advisor has accepted this recommendation.",
  rejected: "Advisor has rejected this recommendation for this student.",
  deferred: "Advisor has deferred this recommendation to a later date.",
  completed: "The accepted recommendation has been carried out.",
};

export const STATUS_BADGE_CLASSES: Record<DecisionStatus, string> = {
  proposed: "bg-slate-100 text-slate-700 border-slate-200",
  accepted: "bg-emerald-100 text-emerald-800 border-emerald-200",
  rejected: "bg-rose-100 text-rose-800 border-rose-200",
  deferred: "bg-amber-100 text-amber-900 border-amber-200",
  completed: "bg-indigo-100 text-indigo-800 border-indigo-200",
};

/**
 * UI affordance helper. `proposed` can move anywhere; the explicit
 * decisions can flip to any other explicit decision (advisors do change
 * their minds); `completed` is treated as terminal but the runtime
 * still accepts an "un-complete" call because tests / demos need it.
 */
export function canTransition(from: DecisionStatus, to: DecisionStatus): boolean {
  if (from === to) return false;
  if (to === "proposed") return false; // clearing a decision goes through `clearDecision`
  return true;
}

/**
 * Phase 11 binding: persisted text must not pretend to validate the
 * causal model. The intervention-tracking server actions assert that
 * advisor notes and follow-up outcomes never contain these phrases.
 *
 * Why the list is short: this is enforcement at the *language* level,
 * not censorship. An advisor writing "the student's grade improved"
 * stays — we only forbid claims like "proves the model is causally
 * correct".
 */
export const BANNED_PHRASES: ReadonlyArray<string> = [
  "guaranteed",
  "proven cause",
  "confirms causation",
  "scientific proof",
];

export function containsBannedLanguage(text: string | null | undefined): string | null {
  if (!text) return null;
  const lower = text.toLowerCase();
  for (const phrase of BANNED_PHRASES) {
    if (lower.includes(phrase)) return phrase;
  }
  return null;
}

/** Convenience: the verb used in the timeline ("Advisor accepted …"). */
export const STATUS_VERB: Record<DecisionStatus, string> = {
  proposed: "proposed",
  accepted: "accepted",
  rejected: "rejected",
  deferred: "deferred",
  completed: "marked complete",
};
